import { type Edge, MarkerType } from 'reactflow';

export const initialEdges: Edge[] = [
  {
    id: 'e-unstructured-unified-dashed',
    source: 'unstructured',
    target: 'ocr',
    animated: true,
    type: 'smoothstep',
    style: {
      stroke: 'rgba(100,116,139,0.55)',
      strokeWidth: 2,
      strokeDasharray: '4 6',
      strokeLinecap: 'round',
    },
  },
  {
    id: 'e-unstructured-ocr',
    source: 'ocr',
    target: 'llm',
    animated: true,
    type: 'smoothstep',
    style: {
      stroke: 'rgba(100,116,139,0.55)',
      strokeWidth: 2,
      strokeDasharray: '4 6',
      strokeLinecap: 'round',
    },
  },
  {
    id: 'e-unstructured-llm',
    source: 'llm',
    target: 'unified',
    targetHandle: 'top-center',
    animated: true,
    type: 'smoothstep',
    style: {
      stroke: 'rgba(100,116,139,0.55)',
      strokeWidth: 2,
      strokeDasharray: '4 6',
      strokeLinecap: 'round',
    },
  },
  {
    id: 'e-unstructured-unified-dashed',
    source: 'structured',
    target: 'unified',
    animated: true,
    type: 'smoothstep',
    style: {
      stroke: 'rgba(100,116,139,0.55)',
      strokeWidth: 2,
      strokeDasharray: '4 6',
      strokeLinecap: 'round',
    },
  },
  {
    id: 'e-privue-unified-dashed',
    source: 'privue',
    target: 'unified',
    animated: true,
    type: 'smoothstep',
    style: {
      stroke: 'rgba(100,116,139,0.55)',
      strokeWidth: 2,
      strokeDasharray: '4 6',
      strokeLinecap: 'round',
    },
  },
  {
    id: 'e-third-unified-dashed',
    source: 'thirdparty',
    target: 'unified',
    animated: true,
    type: 'smoothstep',
    style: {
      stroke: 'rgba(100,116,139,0.55)',
      strokeWidth: 2,
      strokeDasharray: '4 6',
      strokeLinecap: 'round',
    },
  },

  {
    id: 'e-unified-llm-blue',
    source: 'unified',
    target: 'all-llm',
    animated: true,
    type: 'smoothstep',
    style: { stroke: '#4c6ef5', strokeWidth: 2, strokeLinecap: 'round', strokeLinejoin: 'round' },
    markerEnd: { type: MarkerType.ArrowClosed },
  },
  {
    id: 'ai-agent-target',
    source: 'ai-agent',
    target: 'tool-a',
    targetHandle: 'tool-left',
    animated: true,
    type: 'straight',
    style: { stroke: '#4c6ef5', strokeWidth: 2, strokeLinecap: 'round', strokeLinejoin: 'round' },
    markerEnd: { type: MarkerType.ArrowClosed },
  },
  {
    id: 'ai-agent-source',
    source: 'unified',
    target: 'ai-agent',
    targetHandle: 'tool-left',
    animated: true,
    type: 'straight',
    style: { stroke: '#4c6ef5', strokeWidth: 2, strokeLinecap: 'round', strokeLinejoin: 'round' },
    markerEnd: { type: MarkerType.ArrowClosed },
  },
  {
    id: 'ai-agent-tool-a',
    source: 'ai-agent',
    target: 'tool-a',
    targetHandle: 'tool-left',
    animated: true,
    type: 'straight',
    style: { stroke: '#4c6ef5', strokeWidth: 2, strokeLinecap: 'round', strokeLinejoin: 'round' },
    markerEnd: { type: MarkerType.ArrowClosed },
  },

  {
    id: 'e-unified-models',
    source: 'unified',
    sourceHandle: 'top',
    target: 'agent',
    animated: true,
    type: 'smoothstep',
    style: { stroke: '#4c6ef5', strokeWidth: 2, strokeLinecap: 'round', strokeLinejoin: 'round' },
    markerEnd: { type: MarkerType.ArrowClosed },
  },
  {
    id: 'e-agent-tool-a',
    source: 'agent',
    sourceHandle: 'agent-bottom-center',
    target: 'tool-a',
    animated: true,
    type: 'default',
    style: { stroke: '#4c6ef5', strokeWidth: 1.8, strokeDasharray: '6 6', strokeLinecap: 'round' },
  },
  {
    id: 'e-agent-tool-b',
    source: 'agent',
    sourceHandle: 'agent-bottom-center',
    target: 'tool-b',
    animated: true,
    type: 'default',
    style: { stroke: '#4c6ef5', strokeWidth: 1.8, strokeDasharray: '6 6', strokeLinecap: 'round' },
  },
  {
    id: 'e-agent-tool-c',
    source: 'agent',
    sourceHandle: 'agent-bottom-center',
    target: 'tool-c',
    animated: true,
    type: 'default',
    style: { stroke: '#4c6ef5', strokeWidth: 1.8, strokeDasharray: '6 6', strokeLinecap: 'round' },
  },
  {
    id: 'e-agent-tool-d',
    source: 'agent',
    sourceHandle: 'agent-bottom-center',
    target: 'tool-d',
    animated: true,
    type: 'default',
    style: { stroke: '#4c6ef5', strokeWidth: 1.8, strokeDasharray: '6 6', strokeLinecap: 'round' },
  },
  {
    id: 'e-agent-llm-a',
    source: 'all-llm',
    sourceHandle: 'agent-top-center',
    targetHandle: 'tool-bottom',
    target: 'llm-a',
    animated: true,
    type: 'default',
    style: { stroke: '#4c6ef5', strokeWidth: 1.8, strokeDasharray: '6 6', strokeLinecap: 'round' },
  },
  {
    id: 'e-agent-llm-b',
    source: 'all-llm',
    sourceHandle: 'agent-top-center',
    targetHandle: 'tool-bottom',
    target: 'llm-b',
    animated: true,
    type: 'default',
    style: {
      stroke: 'rgba(148,163,184,0.55)',
      strokeWidth: 1.8,
      strokeDasharray: '6 6',
      strokeLinecap: 'round',
    },
  },
  {
    id: 'e-agent-llm-c',
    source: 'all-llm',
    sourceHandle: 'agent-top-center',
    targetHandle: 'tool-bottom',
    target: 'llm-c',
    animated: true,
    type: 'default',
    style: {
      stroke: 'rgba(148,163,184,0.55)',
      strokeWidth: 1.8,
      strokeDasharray: '6 6',
      strokeLinecap: 'round',
    },
  },
  {
    id: 'e-agent-llm-d',
    source: 'all-llm',
    sourceHandle: 'agent-top-center',
    targetHandle: 'tool-bottom',
    target: 'llm-d',
    animated: true,
    type: 'default',
    style: {
      stroke: 'rgba(148,163,184,0.55)',
      strokeWidth: 1.8,
      strokeDasharray: '6 6',
      strokeLinecap: 'round',
    },
  },

  // optional faint connector
  {
    id: 'e-unified-llm-neutral',
    source: 'unified',
    target: 'llm-models',
    animated: false,
    type: 'smoothstep',
    style: { stroke: 'rgba(71,85,105,0.12)', strokeWidth: 2 },
  },
  {
    id: 'e-models-response',
    source: 'agent',
    target: 'live-chat',
    animated: true,
    type: 'straight',
    style: { stroke: '#4c6ef5', strokeWidth: 2, strokeLinecap: 'round' },
    markerEnd: { type: MarkerType.ArrowClosed },
  },
  {
    id: 'e-models-response',
    source: 'llm-models',
    target: 'response',
    animated: true,
    type: 'smoothstep',
    style: { stroke: '#16a34a', strokeWidth: 2, strokeLinecap: 'round' },
    markerEnd: { type: MarkerType.ArrowClosed },
  },
  // {
  //     id: "e-models-response",
  //     source: "llm-models",
  //     target: "response",
  //     animated: true,
  //     type: "smoothstep",
  //     style: { stroke: "#16a34a", strokeWidth: 2, strokeLinecap: "round" },
  //     markerEnd: { type: MarkerType.ArrowClosed },
  // }
];
