/* Auto-generated by scripts/generate-article-index.mjs */
export type ArticleMeta = {
  slug: string;
  title: string;
  date: string; // ISO
  author: string | null;
  summary: string;
  tags: string[];
  articleType: string | null;
  solutionName: string | null;
  solutionLink: string | null;
  coverImage: string;
  readTime: string;
  file: string;
  url: string;
};

export const articles: ArticleMeta[] = [
  {
    "slug": "supply-chain-resilience-2",
    "title": "Enhancing Supply Chain Resilience 2",
    "date": "2025-04-21",
    "author": "Saurabh Verma",
    "summary": "PRIVUE's perpetual vendor risk monitoring platform transforms supply chain resilience by integrating thousands of data sources, continuously assessing vendor stability, and providing actionable intelligence that enables procurement and operations teams to identify emerging risks, implement proactive interventions, and maintain operational continuity even during widespread disruptions.",
    "tags": [
      "supply chain",
      "risk",
      "analytics"
    ],
    "articleType": "Case Study",
    "solutionName": "Third-Party Risk Intelligence",
    "solutionLink": "#",
    "coverImage": "https://plus.unsplash.com/premium_photo-1744944778150-12afe488303e",
    "readTime": "3 min",
    "file": "src/data/articles/supabaseBlog.mdx",
    "url": "/articles/supply-chain-resilience-2"
  },
  {
    "slug": "supply-chain-resilience",
    "title": "Enhancing Supply Chain Resilience",
    "date": "2025-04-20",
    "author": "Saurabh Verma",
    "summary": "PRIVUE's perpetual vendor risk monitoring platform transforms supply chain resilience by integrating thousands of data sources, continuously assessing vendor stability, and providing actionable intelligence that enables procurement and operations teams to identify emerging risks, implement proactive interventions, and maintain operational continuity even during widespread disruptions.",
    "tags": [
      "supply chain",
      "risk",
      "analytics"
    ],
    "articleType": "Case Study",
    "solutionName": "Third-Party Risk Intelligence",
    "solutionLink": "#",
    "coverImage": "https://plus.unsplash.com/premium_photo-1744944778150-12afe488303e",
    "readTime": "4 min",
    "file": "src/data/articles/cs1.mdx",
    "url": "/articles/supply-chain-resilience"
  }
];

/** Dynamic import map to get the MDX component on demand */
export const loaders: Record<string, () => Promise<any>> = {
  "supply-chain-resilience-2": () => import("/src/data/articles/supabaseBlog.mdx"),
  "supply-chain-resilience": () => import("/src/data/articles/cs1.mdx")
};
