/* Auto-generated by scripts/generate-article-index.mjs */
export type ArticleMeta = {
  slug: string;
  title: string;
  date: string; // ISO
  author: string | null;
  summary: string;
  tags: string[];
  articleType: string | null;
  solutionName: string | null;
  solutionLink: string | null;
  coverImage: string;
  readTime: string;
  file: string;
  url: string;
};

export const articles: ArticleMeta[] = [
  {
    "slug": "strengthening-insolvency-investigations",
    "title": "Strengthening Insolvency Investigations",
    "date": "2025-06-04",
    "author": "Saurabh Verma",
    "summary": "Accelerating Asset Recovery Through Advanced Data Intelligence",
    "tags": [
      "insolvency",
      "asset recovery",
      "risk intelligence",
      "bankruptcy",
      "compliance"
    ],
    "articleType": "Case Study",
    "solutionName": "Insolvency Investigations",
    "solutionLink": "solutions/entity-due-diligence",
    "coverImage": "/articles-test-images/insolvency.jpg",
    "readTime": "4 min",
    "file": "src/data/articles/strengthening-insolvency-investigations.mdx",
    "url": "/articles/strengthening-insolvency-investigations"
  },
  {
    "slug": "redefining-commercial-lines-underwriting",
    "title": "Redefining Commercial Lines Underwriting",
    "date": "2025-05-28",
    "author": "Saurabh Verma",
    "summary": "Unlocking Superior Risk Intelligence for Liability Insurance",
    "tags": [
      "underwriting",
      "insurance",
      "risk intelligence",
      "liability",
      "analytics"
    ],
    "articleType": "Case Study",
    "solutionName": "Commercial Lines Underwriting",
    "solutionLink": "solutions/commercial-insurance-underwriting",
    "coverImage": "/articles-test-images/commercial-lines-2.jpg",
    "readTime": "3 min",
    "file": "src/data/articles/redefining-commercial-lines-underwriting.mdx",
    "url": "/articles/redefining-commercial-lines-underwriting"
  },
  {
    "slug": "optimising-distributor-credit-management",
    "title": "Optimising Distributor Credit Management",
    "date": "2025-05-20",
    "author": "Saurabh Verma",
    "summary": "Optimizing Financial Performance Through Data-Driven Credit Decisions",
    "tags": [
      "credit risk",
      "distributor",
      "financial performance",
      "analytics",
      "B2B"
    ],
    "articleType": "Case Study",
    "solutionName": "Distributor Credit Management",
    "solutionLink": "solutions/distributor-performance-management",
    "coverImage": "/articles-test-images/distributor-credit-risk.jpg",
    "readTime": "2 min",
    "file": "src/data/articles/optimising-distributor-credit-management.mdx",
    "url": "/articles/optimising-distributor-credit-management"
  },
  {
    "slug": "mitigating-risk-in-global-supplier-selection",
    "title": "Mitigating Risk in Global Supplier Selection",
    "date": "2025-05-12",
    "author": "Saurabh Verma",
    "summary": "Building Resilient Supply Chains Through Advanced Compliance and Risk Analytics",
    "tags": [
      "supplier risk",
      "compliance",
      "supply chain",
      "analytics",
      "global trade"
    ],
    "articleType": "Case Study",
    "solutionName": "Supplier Risk Intelligence",
    "solutionLink": "solutions/third-party-risk-management",
    "coverImage": "/articles-test-images/global-supplier-risk.jpg",
    "readTime": "3 min",
    "file": "src/data/articles/mitigating-risk in-global-supplier-selection.mdx",
    "url": "/articles/mitigating-risk-in-global-supplier-selection"
  },
  {
    "slug": "transforming-credit-risk-assessment",
    "title": "Transforming Credit Risk Assessment Through Alternative Data",
    "date": "2025-04-21",
    "author": "Saurabh Verma",
    "summary": "Unlocking New Dimensions of Credit Intelligence for Financial Institutions",
    "tags": [
      "credit risk",
      "alternative data",
      "financial services",
      "MSME",
      "analytics"
    ],
    "articleType": "Case Study",
    "solutionName": "Credit Risk Assessment",
    "solutionLink": "solutions/third-party-risk-management",
    "coverImage": "/articles-test-images/credit-risk-2.jpg",
    "readTime": "4 min",
    "file": "src/data/articles/transforming-credit-risk-assessment.mdx",
    "url": "/articles/transforming-credit-risk-assessment"
  },
  {
    "slug": "enhancing-supply-chain-resilience",
    "title": "Enhancing Supply Chain Resilience",
    "date": "2025-04-20",
    "author": "Saurabh Verma",
    "summary": "Intelligent Vendor Risk Monitoring for Operational Stability ",
    "tags": [
      "supply chain",
      "risk",
      "analytics"
    ],
    "articleType": "Case Study",
    "solutionName": "Third-Party Risk Intelligence",
    "solutionLink": "solutions/third-party-risk-management",
    "coverImage": "/articles-test-images/supply-chain.jpg",
    "readTime": "4 min",
    "file": "src/data/articles/enhancing-supply-chain-resilience.mdx",
    "url": "/articles/enhancing-supply-chain-resilience"
  }
];


/** Dynamic import map to get the MDX component on demand */
export const loaders: Record<string, () => Promise<any>> = {
  "strengthening-insolvency-investigations": () => import("./strengthening-insolvency-investigations.mdx"),
  "redefining-commercial-lines-underwriting": () => import("./redefining-commercial-lines-underwriting.mdx"),
  "optimising-distributor-credit-management": () => import("./optimising-distributor-credit-management.mdx"),
  "mitigating-risk-in-global-supplier-selection": () => import("./mitigating-risk in-global-supplier-selection.mdx"),
  "transforming-credit-risk-assessment": () => import("./transforming-credit-risk-assessment.mdx"),
  "enhancing-supply-chain-resilience": () => import("./enhancing-supply-chain-resilience.mdx")
};
